### ISSUE TITLE
启用插件后，打包工程报错

### ISSUE THREAD

**Issue by yuxueliyuxl** [AdrianPanGithub/HoudiniEngineForUnreal#1]
UATHelper: 打包 (Windows): D:\Program Files\Epic Games\UE_5.4\Engine\Plugins\Marketplace\HoudiniEngineForUnreal-UE5_4\Source\HoudiniEngine\Public\HoudiniEngineCommon.h(26): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: 打包 (Windows): D:\Program Files\Epic Games\UE_5.4\Engine\Plugins\Marketplace\HoudiniEngineForUnreal-UE5_4\Source\HoudiniEngine\Public\HoudiniEngineCommon.h(29): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: 打包 (Windows): D:\Program Files\Epic Games\UE_5.4\Engine\Plugins\Marketplace\HoudiniEngineForUnreal-UE5_4\Source\HoudiniEngine\Public\HoudiniEngineCommon.h(32): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: 打包 (Windows): D:\Program Files\Epic Games\UE_5.4\Engine\Plugins\Marketplace\HoudiniEngineForUnreal-UE5_4\Source\HoudiniEngine\Public\HoudiniEngineCommon.h(35): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
PackagingResults: Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.
UATHelper: 打包 (Windows): D:\Program Files\Epic Games\UE_5.4\Engine\Plugins\Marketplace\HoudiniEngineForUnreal-UE5_4\Source\HoudiniEngine\Public\HoudiniEngineCommon.h(38): Error: An explicit Category specifier is required for any property exposed to the editor or Blueprints in an Engine module.

**Comment by AdrianPanGithub** [comment]
抱歉好久没测试打包了我先临时把HoudiniEngine这个Module改成Editor了，可以拉一下UE5_4分支，我明天再看一下这个问题

**Comment by AdrianPanGithub** [comment]
我修复了打包问题，现在插件是editor-only了。Houdini TA请在HDA输出上加i@unreal_split_actors = 1，或者Bake，来对生成结果进行打包

**Comment by yuxueliyuxl** [comment]
谢谢，辛苦了
