### ISSUE TITLE
可能是bug

### ISSUE THREAD

**Issue by godthief** [AdrianPanGithub/HoudiniEngineForUnreal#2]
上次有一个疑似bug的地方忘记说了，还是以he_example_quick_shape为例
1.在houdiniengine模式下，选中Edit选项，点击下拉框选中distance属性，（我的理解是有一个球体代表画笔，然后输入distance的参数，就可以画笔选中模型的哪些prim，这些prim就挤出对应数值），现在是输入参数——选prim——挤出，参数就归零了，不知道是不是bug，同样的现在还不支持先选prim在输入数值（这里指的是以笔刷形式选中，而不是鼠标点击prim选中）

2.画笔选prim的时候在没碰撞的情况下，选不中，在场景中，我把hda放置在默认关卡，只能用画笔选中挨着Floor部分的prim

3.还有个操作比较奇怪的，就是在选中画笔状态下，不小心选中别的actor后，还得在选中hda后，选中面，然后再设置画笔属性，（如果能保留上一次的操作属性类似，会不会好一点）

以上是一些小反馈，可能跟作者的设计初衷不一样，在这里只是交流一下

上次提的bug已经修复了，👍感谢大佬

**Comment by ChildAdrian** [comment]
非常感谢这三个bug反馈，目前edit里这个 属性笔刷功能 确实还没有开发完成。
之前以为没人会用到这个功能，没想到确实有在被测试到。
我会在下一个版本中对属性笔刷功能做一定完善。

**Comment by ChildAdrian** [comment]
第一个问题已经修复了。第二个选中的actor unreal确实不支持碰撞检测，第三个是出于确保变化信息正确性的考虑会强制清除上次的选择内容
